[workspace]
members = [
    "src/checkmark_cli",
    "src/checkmark_fmt",
    "src/checkmark_link_checker",
    "src/checkmark_lint",
    "src/checkmark_ls",
    "src/checkmark_open_ai",
    "src/checkmark_spelling",
    "src/common",
]
resolver = "2"
