[global]
exclude = [         
    "*LICENSE*",
    "*/.github/*",
    "*/tests/*",
    "*/src/*",
]

[style]
headings="consistent"
unordered_lists="consistent"
num_spaces_after_list_marker=1
bold="consistent"

[fmt]
check=false
show_diff=false

[link_checker]
ignore_wildcards=["**gffffffffffoooooogel**", "/**.rs"]
timeout=10
max_retries=1
user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"

[linter]
allowed_html_tags=["img"]

[review]                          
no_suggestions=false
creativity=10

[compose]
creativity=80

[spelling]
words_whitelist=[]
