[global]
exclude = [         
    "*LICENSE*",
    "*/.github/*",
    "*/tests/*",
    "*/src/*",
]

[style]
headings = "consistent"
unordered_lists = "consistent"
bold = "consistent"

[fmt]
check = false
show_diff = false

[link_checker]
ignore_wildcards=["**gffffffffffoooooogel**", "/**.rs"]

[linter]
allowed_html_tags = []

[review]                          
no_suggestions=false
creativity=10

[spelling]
words_whitelist=[
    "additnal",
    "API",
    "behavior",
    "checkmark",
    "dotenv",
    "OpenAI",
    "GoogleTest",
    "CLI",
    "URL",
    "SARIF",
    "OPEN_AI_API_KEY"
]
