# This TOML file is used to configure checkmark for your project
# Configuration is split by sections
# Every tool has its own section + sections for options that are shared between tools

# Global options shared across all tools
[global]
# List of file glob patterns to ignore when discovering Markdown files
exclude = [         
    "*LICENSE*",
    "*/.github/*",
    "*/tests/*",
    "*/src/*",
]

# Common style options of your project
# These options affects fmt and linter
# Used to enforce the same style across all Markdown files
# If not specified, the style will be inferred from the first element in the file
[style]
# Heading style to enforce, e.g. "atx" or "setext"
# Possible values are: "atx", "setext" or "consistent"
# Read to understand the difference: https://www.markdownguide.org/basic-syntax/#headings
headings = "consistent"
# Unordered list style to enforce, e.g. "asterisk", "plus" or "dash"
# Possible values are: "asterisk", "plus", "dash" or "consistent"
# Read to understand the difference: https://www.markdownguide.org/basic-syntax/#lists-1
unordered_lists = "consistent"
# Bold(string) emphasis element style to enforce, e.g. "asterisk" or "underscore"
# Possible values are: "asterisk", "underscore" or "consistent"
# Read to understand the difference: https://www.markdownguide.org/basic-syntax/#bold
bold = "consistent"

# Formatter-specific options   
[fmt]
# Check mode - when true, fmt will only print the diff without applying it
# and exit with status code 1 if any formatting issues are found
check = true
# When true + "--check" flag, fmt will print the full diff 
show_diff = true

# Link checker-specific options
[link_checker]
# List of glob URI patterns to ignore when checking links
ignore_wildcards=["**gffffffffffoooooogel**", "/**.rs"]

# Linter-specific options
[linter]
# List of HTML elements to ignore when linting, e.g. "a", "img", etc.
allowed_html_tags = []

# Review-specific options
[review]       
# When true, the review will be printed without fix suggestions                     
no_suggestions=false
# Custom prompt for the review, e.g. "Make a grammar review"
# prompt="Make a grammar review"

# Spelling-specific options
[spelling]
# List of words to ignore while spell checking
words_whitelist=[
    "additnal",
    "API",
    "behavior",
    "checkmark",
    "dotenv",
    "OpenAI",
    "GoogleTest",
    "CLI",
    "URL",
    "SARIF",
    "OPEN_AI_API_KEY"
]
