[package]
name = "checkmark_ls"
description = "Library that lists Markdown files in provided dir"
version = "0.0.1"
edition = "2021"

[dependencies]
common = { path = "../common" }

glob = "0.3.1"
log = "0.4.20"
