[package]
name = "checkmark_ls"
description = "Library that lists Markdown files in provided dir"
version = "0.0.1"
edition = "2021"

[dependencies]
common = { path = "../common" }

glob = "0.3.1"
log = "0.4.20"
is-url = "1.0.4"
reqwest = { versioj="0.11.22", features = ["blocking", "json"] }
tempfile = "3.8.1"
