[package]
name = "checkmark_cli"
description = "CLI tool that help keep your Markdown documentation at hight quality."
version = "0.1.0"
edition = "2021"

[dependencies]
checkmark_fmt = { path = "../checkmark_fmt" }
checkmark_lint = { path = "../checkmark_lint" }
checkmark_ls = { path = "../checkmark_ls" }
checkmark_open_ai = { path = "../checkmark_open_ai" }
common = { path = "../common" }

clap = { version = "4.4.11", features = [ "derive", "cargo" ] }
tokio = { version = "1.32.0", features = ["full"] }
serde-sarif = "0.4.2"
serde_json = "1.0.107"
spinners = "4.1.0"
env_logger = "0.10.1"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"