# This TOML file is used to configure checkmark for your project.
# Configuration is split by sections. Every tool has its own section
# + sections for options that are shared between tools


##############################  Global  #############################
[global]
# List of file patterns to ignore when discovering Markdown files.
# Example: ["*LICENSE*", "*/.github/*"]  
exclude = []


##############################  Style  ##############################
# Configure Markdown code style. Affects fmt and linter. When not
# specified then style is inferred from the first element in a file
[style]
# Heading.
# Possible values are: "atx", "setext" or "consistent"
# Reference: https://www.markdownguide.org/basic-syntax/#headings
headings = "consistent"
# Unordered list.
# Possible values are: "asterisk", "plus", "dash" or "consistent"
# Reference: https://www.markdownguide.org/basic-syntax/#lists-1
unordered_lists = "consistent"
# Bold(string) emphasis.
# Possible values are: "asterisk", "underscore" or "consistent"
# Reference: https://www.markdownguide.org/basic-syntax/#bold
bold = "consistent"


############################  Formatter  ############################
[fmt]
# Enables check mode. When enabled then fmt will only print the diff
# without applying it. Exit with status code "1" if any formatting
# issues are found and "0" otherwise
check = false
# When used with check then fmt will print the full diff instead of
# a summary. Use it to see how your file is going to be formatted
# before applying the changes
show_diff = false


##########################  Link Checker  ###########################
[link_checker]
# List of glob URI patterns to ignore when checking links
# Can be used for both hyperlinks and file links
# Example: ["**this-host-will-be-ignored**", "/**.rs"]
ignore_wildcards=[]


#############################  Linter  ##############################
[linter]
# List of HTML elements to ignore when linting, e.g. "a", "img", etc.
# Example: ["a", "img"]
allowed_html_tags = []


#############################  Open AI  #############################
[open_ai]
# Use this to provide Open AI API key.
# You can get it from https://platform.openai.com/account/api-keys
# WARN: This option is meant to be used just for testing
#       Do not ever commit your API key to your repo
#       Use environment variables or .env files instead
# api_key = ""

#############################  Review  ##############################
[review]       
# When true, the review will be printed without fix suggestions                     
no_suggestions=false
# Controls how creative AI will be while generating suggestions
# Higher values will result in less predictable result
# Min valus is 0 and max value is 100. Default is 10
creativity=10
# Custom prompt for the review
# Example: "Make a grammar review"
# prompt="Make a grammar review"


############################  Compose  ##############################
[compose]
# Controls how creative AI will be while generating a file
# Higher values will result in less predictable result
# Min valus is 0 and max value is 100. Default is 10
creativity=10


########################## Spell Checker  ###########################
[spelling]
# List of words to ignore while spell checking
# Example: ["checkmark", "CLI", "SARIF", "OPEN_AI_API_KEY"]
words_whitelist=[]
